### ISSUE TITLE
Installation Guide

### ISSUE THREAD

**Issue by martnst** [rajlaud/victron-ble-ha-parser#1]
Hey, instructions for installation would be great to have. 

Cheers

**Comment by rajlaud** [comment]
I updated the [README](https://github.com/rajlaud/victron-ble-ha-parser/blob/main/README.md) with some installation instructions. Right now this is just for testing; the goal is to integrate into HA core.

**Comment by martnst** [comment]
Thx @rajlaud. 
Would be nice to link the pending PRs, to understand where things are stuck. 
I found this one here: https://github.com/keshavdv/victron-ble/pull/48

What do you think of finishing a version without "Smart Battery Protect"? I e.g. don't have one on my system. 

Thanks

**Comment by rajlaud** [comment]
The testing version I run relies on code from these unmerged PRs:

- https://github.com/keshavdv/victron-ble/pull/48
- https://github.com/keshavdv/victron-ble/pull/47

I'm not sure how actively `victron-ble` is being maintained. I'm considering incorporating the relevant code directly into the `victron-ble-ha-parser` plugin.
